/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/test": {
    /** Test */
    get: operations["TechTestWeb.TestController.index"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * Test 
     * @description Test Schema 
     * @example {
     *   "hello": "world"
     * }
     */
    Test: {
      /** @description Test Property (world) */
      hello: string;
    };
    /**
     * TestResponse 
     * @description Test Response Schema 
     * @example {
     *   "data": {
     *     "hello": "world"
     *   }
     * }
     */
    TestResponse: {
      data?: components["schemas"]["Test"];
    };
  };
  responses: {
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  "TechTestWeb.TestController.index": {
    /** Test */
    responses: {
      /** @description Test */
      200: {
        content: {
          "application/json": components["schemas"]["TestResponse"];
        };
      };
    };
  };
}
